import Head from 'next/head';
import { useState } from 'react';
import { HiOutlineSun, HiOutlineMoon } from 'react-icons/hi';
import { AiFillGithub, AiFillInstagram, AiFillLinkedin } from 'react-icons/ai';

import Image from 'next/image';

import devRS from '../public/perfil.png';
import design from '../public/design.png';
import code from '../public/code.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import ScrollToTop from 'react-scroll-to-top';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <meta charSet='UTF-8' />
        <title>Portfolio Rodrigo Silva</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 ease-in-out relative' id='home'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-200'>devrodrigo</h1>
            <ul className='flex items-center '>
              <li>
                <HiOutlineSun
                  className='cursor-pointer text-3xl hidden dark:text-gray-200 dark:block'
                  onClick={() => setDarkMode(!darkMode)}
                />
                <HiOutlineMoon
                  className='cursor-pointer text-3xl dark:hidden'
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                  href='#contato'
                >
                  Contato
                </a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Rodrigo Silva</h2>
            <h3 className='text-2xl py-3 md:text-3xl dark:text-gray-200'>Desenvolvedor Web e Mobile</h3>
            <p className='text-base py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto'>Amante de tecnologia e suas possibilidades, busco constantemente aprender e aprimorar minhas Skills para poder solucionar problemas e oportunidades.</p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <a target={'_blank'} rel="noreferrer noopener" href='https://bit.ly/3MdLzFi'><AiFillLinkedin /></a>
            <a target={'_blank'} rel="noreferrer noopener" href='https://bit.ly/3Mc3bBi'><AiFillInstagram /></a>
            <a target={'_blank'} rel="noreferrer noopener" href='https://bit.ly/3rVys2p'><AiFillGithub /></a>
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={devRS} layout='fill' objectFit='cover' alt='Ilustraçao cartonizada de Rodrigo' />
          </div>

        </section>

        <section>
          <div className='text-center p-10 mt-10'>
            <h3 className='text-3xl py-1 mb-5 text-teal-500'>O que eu ofereço</h3>
            <p className='text-base py-2 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto'>
              Procuro me empenhar e oferecer o meu melhor nos projetos, sempre em sintonia com o cliente/equipe. Fazendo uso das melhores ferramentas presentes no mercado.
            </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='flex-1 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100} alt='representação de uma paisagem' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Design</h3>
              <p className='py-2'>Transformamos sua ideia em um design elegante e atual.</p>
              <h4 className='py-4 text-teal-600'>Ferramentas que eu uso</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='flex-1 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100} alt='representação de hashtag' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Códigos</h3>
              <p className='py-2'>Procuro sempre empregar as tecnologias mais atuais e fomentadas na comunidade.</p>
              <h4 className='py-4 text-teal-600'>Tecnologias que eu uso</h4>
              <p className='text-gray-800 py-1'>HTML | CSS | JavaScript</p>
              <p className='text-gray-800 py-1'>TypeScript</p>
              <p className='text-gray-800 py-1'>React JS</p>
              <p className='text-gray-800 py-1'>React Native</p>
              <p className='text-gray-800 py-1'>Tailwind CSS</p>
            </div>
          </div>
        </section>
        <section>
          <div className='text-center p-10'>
            <h3 className='text-3xl py-1 text-teal-500 mb-5'>
              Portfolio
            </h3>
            <p className='text-base py-2 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto'>
              Estes são alguns dos meus projetos, utilizados tanto para estudo quanto para <span className='text-teal-500'>Freelance</span>.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                layout='responsive'
                height={'100%'}
                src={web1}
                alt='imagem referente a um projeto' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                layout='responsive'
                height={'100%'}
                src={web2}
                alt='imagem referente a um projeto' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                layout='responsive'
                height={'100%'}
                src={web3}
                alt='imagem referente a um projeto' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                layout='responsive'
                height={'100%'}
                src={web4}
                alt='imagem referente a um projeto' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                layout='responsive'
                height={'100%'}
                src={web5}
                alt='imagem referente a um projeto' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                className='rounded-lg object-cover'
                width={'100%'}
                layout='responsive'
                height={'100%'}
                src={web6}
                alt='imagem referente a um projeto' />
            </div>
          </div>
        </section>
        <section id='contato'>
          <div className='text-center pt-10'>
            <h3 className='text-lg py-1 text-gray-800 dark:text-gray-200 md:text-xl'>
              Precisa de um desenvolvedor?
            </h3>
          </div>
          <div>
            <a href='https://bit.ly/3fOoJYS'
              target={'_blank'} rel="noreferrer noopener"
              className='flex text-center items-center justify-center text-teal-500'
            >
              <span className='text-2xl md:text-3xl underline'>Vamos trabalhar juntos ⇾</span>
            </a>
          </div>
        </section>
        <footer>

          <ScrollToTop
            color='white'
            style={{ right: 30, backgroundColor: '#14b8a6' }}
            className='flex text-center justify-center items-center'
          />

          <div className='h-40 w-full bg-gray-200 rounded-t-xl mt-10'>
            <h3 className='p-5'>Qualquer coisa aqui</h3>
          </div>
        </footer>
      </main>
    </div>
  )
}
