import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillGithub, AiFillInstagram, AiFillLinkedin } from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Rodrigo Silva</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbyed</h1>
            <ul className='flex items-center '>
              <li>
                <BsFillMoonStarsFill
                  className='cursor-pointer text-2xl'
                />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                  href='#'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Rodrigo Silva</h2>
            <h3 className='text-2xl py-2'>Desenvolvedor Web e Mobile</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Amante de tecnologia e suas possibilidades, busco constantemente aprender e aprimorar minhas Skills para poder solucionar problemas e oportunidades. Vamos trabalhar juntos?</p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin />
            <AiFillInstagram />
            <AiFillGithub />
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout='fill' objectFit='cover' alt='Ilustraçao cartonizada de Rodrigo' />
          </div>

        </section>
      </main>
    </div>
  )
}
